# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 09:52
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('restaurant_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('yelp_id', models.CharField(max_length=255)),
            ],
        ),
    ]
