# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 10:32
from __future__ import absolute_import
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodtrain.Train')),
            ],
        ),
    ]
