# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 10:53
from __future__ import absolute_import
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrain', '0002_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='train',
            options={'ordering': ('-start_time',)},
        ),
        migrations.AddField(
            model_name='train',
            name='creator',
            field=models.CharField(default='Per', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='foodtrain.Train'),
        ),
    ]
