# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 14:39
from __future__ import absolute_import
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrain', '0004_remove_train_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='train',
        ),
        migrations.AddField(
            model_name='train',
            name='publications',
            field=models.ManyToManyField(to='foodtrain.Participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creators', to='foodtrain.Participant'),
        ),
        migrations.AlterField(
            model_name='train',
            name='yelp_id',
            field=models.CharField(max_length=255, unique_for_date='start_time'),
        ),
    ]
