# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 14:40
from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtrain', '0005_auto_20161110_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='publications',
            new_name='participants',
        ),
    ]
